jdnotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^entries/', include('notes.urls', namespace='entries')),
    url(r'^accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.conf.urls import url

from notes.views import entry_list, entry_detail, entry_create, entry_update, entry_delete

urlpatterns = [
    url(r'^$', entry_list, name='list'),
    url(r'^create/$', entry_create, name='create'),
    url(r'^(?P<id>\d+)/$', entry_detail, name='detail'),
	url(r'^(?P<id>\d+)/update/$', entry_update, name='edit'),
	url(r'^(?P<id>\d+)/delete/$', entry_delete, name='delete')
]

notes/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Entry(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL) 
	title = models.CharField(max_length=120)
	description = models.TextField()
	timestamp = models.DateTimeField(auto_now_add=True) #The moment it's created
	updated = models.DateTimeField(auto_now=True) #The moment its updated
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return "/entries/{0}/".format(self.id)

	def get_update_url(self):
		return "/entries/{0}/update/".format(self.id)

	def get_delete_url(self):
		return "/entries/{0}/delete/".format(self.id)

notes/forms.py
from django import forms

from .models import Entry

class EntryForm(forms.Form):
	title = forms.CharField()
	description = forms.CharField()
	image = forms.ImageField()

'''
class EntryModelForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['title', 'description', 'image']
'''

notes/views.py
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from .forms import EntryForm
from .models import Entry

@login_required
def entry_list(request):
	entries = Entry.objects.filter(user=request.user)
	query = request.GET.get("q")
	if query:
		entries = entries.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)
					).distinct()
	context = {
		'object_list': entries
	}
	return render(request, "notes/entries.html", context)


@login_required
def entry_detail(request, id):
	note = get_object_or_404(Entry, id=id)
	context = {
		'object': note
	}
	return render(request, "notes/entries_detail.html", context)


@login_required
def entry_create(request):
	form = EntryForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		title = request.POST.get("title")
		description = request.POST.get("description")
		image = request.FILES.get("image")

		entry = Entry()
		entry.title = title
		entry.description = description
		entry.image = image
		entry.user = request.user
		entry.save()
		print(entry)

		# For the model form
		#form.instance.user = request.user
		#form.save()
		#entry_id = form.instance.id
		#entry = get_object_or_404(Entry, id=entry_id)
		messages.info(request, 'Created a New Note.')
		return redirect(entry.get_absolute_url())
	context = {
		'form': form
	}

	return render(request, "notes/entries_create.html", context)

@login_required
def entry_update(request, id):
	instance = get_object_or_404(Entry, id=id)
	form = EntryForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		form.save()
		entry_id = form.instance.id
		entry = get_object_or_404(Entry, id=entry_id)
		messages.info(request, 'Succesfully update your Note.')
		return redirect(entry.get_absolute_url())
	context = {
		'form': form,
		'instance': 'object'
	}

	return render(request, "notes/entries_update.html", context)		

@login_required
def entry_delete(request, id):
	entry = get_object_or_404(Entry, id=id)
	if entry.user != request.user:
		response = HttpResponse("You don't have permission to delete this note.")
		response.status_code = 403
		return response

	if request.method == "POST":
		entry.delete()
		messages.info(request, "This note has been successfully deleted.")
		return redirect("/entries/")

	context = {
		'object': entry
	}
	return render(request, "notes/entries_delete.html", context)

notes/templates/notes/entries.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-offset-3 col-sm-6">
			<h1>My Entries</h1>
			<table class="table">
					{% for object in object_list %}
					<p><a href="{{ object.get_absolute_url }}">{{ object.title }}</a> - {{ object.timestamp|timesince }} ago</p>
					<hr>
					{% endfor %}
			</table>
		</div>
	</div>
</div>

{% endblock content %}

notes/templates/notes/entries_create.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-offset-3 col-sm-6">
			<h1>Create a New Note</h1>
			{% include 'form.html' with form=form %}
		</div>
	</div>
</div>

{% endblock content %}

notes/templates/notes/entries_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">

		<div class="col-sm-offset-3 col-sm-6">
			<h3>Are you sure you want to delete this note?</h3>
			<form method="POST" action=".">
				{% csrf_token %}
				<input type="submit" class="btn btn-default" name="submit" placeholder="Delete">
			</form>
		</div>
	</div>
</div>

{% endblock content %}

notes/templates/notes/entries_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">

		<div class="col-sm-offset-3 col-sm-6">
					<div class="thumbnail">
			<img src="{{ object.image.url }}">
		</div>
			<h1>{{ object.title }} <small>{{ object.timestamp|timesince }} ago</small></h1>
			<p>{{ object.description }}</p>
			<p>Last Updated: {{ object.updated }}</p>
			<a href="{{ object.get_update_url }}">Update Now</a>
			<a href="{{ object.get_delete_url }}">Delete This Note</a>
		</div>
	</div>
</div>

{% endblock content %}

notes/templates/notes/entries_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-offset-3 col-sm-6">
			<h1>Update this Note</h1>
			<form method="POST" action='.' enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="submit" name="submit" class="btn btn-primary" placeholder="Submit">
				<button class="btn btn-default"><a href="{{ object.get_absolute_url }}"></a>Cancel</button>
			</form>	

		</div>
	</div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
</head>
<body>

{% include 'navbar.html' %}

{% if messages %}
<div class="alert alert-success alert-dismissible container-alert" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
	
{% block content %}			
{% endblock content %}

	
	<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</body>
</html>

templates/form.html
			   <form class='form' method='POST' action='/entries/create/' enctype="multipart/form-data">
			   	{% csrf_token %}
                        <div class='form-group'>
                            <input type='text' class='form-control' name='title' placeholder='Title' /> 
                        </div>
                        <div class='form-group'>
                            <input type='text' class='form-control' name='description' placeholder='Description' />
                        </div>
                        <div class='form-group'>
                            <input type='file' class='form-control' name='image' />
                        </div>
                        <input type="submit" name="submit" class="btn btn-default" placeholder="Submit">
                      </form>

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/entries/">Notes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" name="q" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        
        <li><a href="{% url 'entries:list' %}">My Notepad</a></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% include 'form.html' with form=form %}
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Accounts <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
            <li><a href="/accounts/logout/">Logout</a></li>
            {% else %}
            <li><a href="/accounts/login/">Login</a></li>
            <li><a href="/accounts/signup/">Sign Up</a></li>
            {% endif %}
          </ul>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>